interactions:
- request:
    body: null
    headers:
      Accept:
      - '*/*'
      Accept-Encoding:
      - gzip, deflate
      Connection:
      - keep-alive
      User-Agent:
      - pano-cli/0.7.4
    method: GET
    uri: https://a1.panocdn.com/updates/pano-cli/versions.json
  response:
    body:
      string: '{"latest_version": "0.7.4", "minimum_supported_version": "0.7.4"}'
    headers:
      Accept-Ranges:
      - bytes
      Age:
      - '49'
      Cache-Control:
      - max-age=60
      Connection:
      - keep-alive
      Content-Length:
      - '65'
      Content-Type:
      - application/json
      Date:
      - Thu, 23 Jul 2020 19:07:22 GMT
      ETag:
      - '"6867b00a67be82dc6de1129f91a96f9f"'
      Last-Modified:
      - Thu, 23 Jul 2020 14:02:32 GMT
      Server:
      - AmazonS3
      Via:
      - 1.1 56032fc423a5ce4a2a983fb58385b90d.cloudfront.net (CloudFront)
      X-Amz-Cf-Id:
      - ToRHc05JRCB6yUWZPkppDwYhyt2FoTLz5fQLueaZjJO177Z2mZSu4A==
      X-Amz-Cf-Pop:
      - IAD79-C1
      X-Cache:
      - Hit from cloudfront
      x-amz-replication-status:
      - COMPLETED
      x-amz-version-id:
      - zOCc8ujgfqK83SnQvzD1gK57thi41wdB
    status:
      code: 200
      message: OK
version: 1
