version: '2.4'
services:
  app:
    build:
      dockerfile: .devcontainer/Dockerfile
      context: ..
    environment:
      PYTHONPATH: "/workspace/src"
      PYTHONUNBUFFERED: 1
      HISTFILE: '/root/.bashhistory/.bash_history'
    volumes:
      - ..:/workspace
      - bash-history:/root/.bashhistory
      - $HOME/.ssh:/root/.ssh
      - $HOME/.pip:/root/.pip # TODO: Remove this once our OSS packages are in Pypi
    command: /bin/sh -c "while sleep 1000; do :; done"


volumes:
  vscode-server-extensions:
  bash-history:
